### PR TITLE
Clarifies Exception Cases

### PR DESCRIPTION
**Pull request by alycit**
@mattbaker Take a look.  Modified per our discussion.

### CODE REVIEW

**Comment by sgharms** [comment]
@alycit For my edification. When are they seeing this? Do they know about custom `Exception` class creation or are you letting them return a `String` that represents an error?

**Comment by alycit** [comment]
@sgharms 

Do you mean when in the program?  This is a career week challenge.  

Other challenges in the unit talk about OutOfBoundsExceptions.  Doing this implementation similar to the Java one.

**Comment by mattbaker** [comment]
@sgharms — this is the data structures and algos unit from Onboard. We're adapting it as an experiment to see if it can be delivered post-graduation with a 1/2 time teacher. Experiment results to follow :)

**Comment by mattbaker** [comment]
@alycit — this looks good. We might end up tweaking wording later, but I think we're all still building intuition around what grads can handle with this stuff.

**Pull request merged**
